### ISSUE TITLE
Implement design on "playlists" "page" {1e}

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#5] opened 2017-05-03 12:11 UTC
As in [here](https://github.com/Paratii-Video/paratii-design/blob/master/mvp-design/artboards/mvp-playlist.png)

This depends on #10

**Comment by jellegerbrandy** [comment] 2017-06-07 09:22
duplicate of #10

**Closed as completed by jellegerbrandy** 2017-06-07 09:22 UTC
