### ISSUE TITLE
Not use Modal.show for edit-profile

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-player#267] opened 2017-11-15 09:46 UTC
To open the menu `#edit-profile` use a custom template, and not the Modal.show

```
'click #edit-profile' () {
    // TODO remove this Modal.show
    Modal.show('editProfile')
  }
```

**Comment by bent0b0x** [comment] 2017-11-16 00:49
Hey @eliawk, could you elaborate a bit more as to what the best practices are for modals? i.e. when is it okay to use `Modal.show/showModal` vs. a custom template and why? The implementation I had previously did seem to be working, except on CircleCI tests. Just want to get a better understanding as to why the change is indeed necessary.

FYI I addressed the issue in [this commit](https://github.com/Paratii-Video/paratii-player/pull/266/commits/c1eb8d5397072b78ef4b5b02df8bbc929bb5f6b2)

**Comment by jellegerbrandy** [comment] 2017-11-16 09:55
closing this as the issue is resolved, but if @eliawk wants to explain he is mroe than welcome :-)

**Closed as completed by jellegerbrandy** 2017-11-16 09:55 UTC
Labels: enhancement, refactoring
